### ISSUE TITLE
Can this be updated?

### ISSUE THREAD

**Issue by joeyoropesa-dev** [Tschrock/MineLittlePony-Bedrock#12]
Is this EOL or it is still active?

**Comment by joeyoropesa-dev** [comment]
@Tschrock

**Comment by joeyoropesa-dev** [comment]
And I would love if it's not EOL this port of the plugin to be able to port Alicorn type of ponies 🥰🥰🥰

**Comment by Tschrock** [comment]
I will start working on this project again soon, and yes Alicorns will be included
